apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Version to assign

jobs:
  build-art3:
    steps:
      - uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "art3"
          version: "${{ inputs.version }}"
          url: "docker.io/MyApp/art3:${{ inputs.version }}"
     