apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_call:
    inputs:
      manifest:
        type: string
        required: true
      environment:
         type: string
         required: true  
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
      environment:
        type: string
        required: true       

jobs:
  deploy-art3:
    steps:
      - name: Deploy art3
        if: ${{ fromJSON(inputs.manifest).art3.deploy }}
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: "${{ fromJSON(inputs.manifest).art3.id }}"
          target-environment: "${{ inputs.environment }}"
     