apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_call:
    inputs:
      manifest:
        type: string
        required: true
      environment:
         type: string
         required: true  

jobs:
  deploy-art3:
    steps:
      - name: Deploy art3
        if: ${{ fromJSON(inputs.manifest).art3.deploy }}
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "art3 version: ${{ fromJSON(inputs.manifest).art3.version }}"
          echo "url: ${{ fromJSON(inputs.manifest).art3.url }}"
          echo "env: ${{ inputs.environment }}"
     
