apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Workflow 2


on:
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world from dev branch"
