apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:    

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
  afterbuild:
    needs: build
    steps:
      - name: Say hello build
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello build long prop ${{vars.lengthtest}}"          
  deploy:
    needs: build
    environment: us-env
    steps:
      - name: Deploy to env after approval
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "deploying hello world" 
